import butterChickenImg from "@/assets/dishes/butter-chicken.avif"
import chickenBiryaniImg from "@/assets/dishes/chicken-biryani.jfif"
import muttonBiryaniImg from "@/assets/dishes/mutton-biryani.avif"
import prawnsZabardastImg from "@/assets/dishes/prawns-zabardast.jfif"

export interface MenuItem {
  name: string
  nameAr?: string
  desc: string
  descAr?: string
  price: string
  category: string
  categoryAr?: string
  video?: string
  image?: string
  featured?: boolean
}

// Generated from your menu spreadsheet.
// `desc`/`descAr` were left blank (your sheet has no description column) — add short descriptions any time.
// Add `video: '/videos/filename.mp4'` or `image` (imported asset) to any dish to enable media.
export const menu: MenuItem[] = [
  {
    name: "Sweet Corn Soup Chicken",
    nameAr: "شوربة الذرة الحلوة بالدجاج",
    desc: "",
    price: "11",
    category: "Soups",
    categoryAr: "الشوربات",
  },
  {
    name: "Sweet Corn Soup Vegetable",
    nameAr: "شوربة الذرة الحلوة بالخضار",
    desc: "",
    price: "10",
    category: "Soups",
    categoryAr: "الشوربات",
  },
  {
    name: "Hot & Sour Chicken Soup",
    nameAr: "شوربة حار وحامض بالدجاج",
    desc: "",
    price: "14",
    category: "Soups",
    categoryAr: "الشوربات",
  },
  {
    name: "Hot & Sour Vegetable Soup",
    nameAr: "شوربة حار وحامض بالخضار",
    desc: "",
    price: "11",
    category: "Soups",
    categoryAr: "الشوربات",
  },
  {
    name: "Manchow Soup",
    nameAr: "شوربة مانتشو",
    desc: "",
    price: "14",
    category: "Soups",
    categoryAr: "الشوربات",
  },
  {
    name: "Prawns Soup",
    nameAr: "شوربة روبيان",
    desc: "",
    price: "17",
    category: "Soups",
    categoryAr: "الشوربات",
  },
  {
    name: "Chicken Pakoda (6pcs)",
    nameAr: "باقورا دجاج (٦ قطع)",
    desc: "",
    price: "28",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Reshmi Kabab (6pcs)",
    nameAr: "كباب رشمي (٦ قطع)",
    desc: "",
    price: "28",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Tandoori Chicken (full)",
    nameAr: "دجاج تنوري (كامل)",
    desc: "",
    price: "35",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Tandoori Chicken (Half)",
    nameAr: "دجاج تنوري (نصف)",
    desc: "",
    price: "18",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Chiken Tikka (6pcs)",
    nameAr: "دجاج تكة (٦ قطع)",
    desc: "",
    price: "28",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Malai Kabab (6pcs)",
    nameAr: "كباب مالاي (٦ قطع)",
    desc: "",
    price: "28",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Mutton Sheek Kabab",
    nameAr: "كباب سيخ لحم مفروم",
    desc: "",
    price: "27",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Boti kabab",
    nameAr: "بوتي كباب",
    desc: "",
    price: "32",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Tandoori Prawns (6pcs)",
    nameAr: "روبيان تنوري (٦ قطع)",
    desc: "",
    price: "52",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Kasturi Kabab (6pcs)",
    nameAr: "كاستوري كباب (٦ قطع)",
    desc: "",
    price: "28",
    category: "Tandoori Starter",
    categoryAr: "مقبلات تندوري",
  },
  {
    name: "Kulcha",
    nameAr: "خبز كلتشا",
    desc: "",
    price: "4",
    category: "Tandoori Basket",
    categoryAr: "سلة التندوري",
  },
  {
    name: "Butter Naan",
    nameAr: "خبز نان بالزبدة",
    desc: "",
    price: "5",
    category: "Tandoori Basket",
    categoryAr: "سلة التندوري",
  },
  {
    name: "Pudina Kulcha",
    nameAr: "كلتشا بالنعناع",
    desc: "",
    price: "4",
    category: "Tandoori Basket",
    categoryAr: "سلة التندوري",
  },
  {
    name: "Methi Kulcha",
    nameAr: "كلتشا بالحلبة",
    desc: "",
    price: "4",
    category: "Tandoori Basket",
    categoryAr: "سلة التندوري",
  },
  {
    name: "Chicken Badami Khorma",
    nameAr: "دجاج كورما باللوز",
    desc: "",
    price: "33",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Rada Masala",
    nameAr: "دجاج رادا مسالا",
    desc: "",
    price: "33",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken kali Mirchi",
    nameAr: "دجاج بالفلفل الأسود",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Ashiana",
    nameAr: "دجاج آشيانا",
    desc: "",
    price: "33",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Masala",
    nameAr: "دجاج مسالا",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Kadai",
    nameAr: "دجاج كاداي",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Makhan Wala",
    featured: true,
    image: butterChickenImg,
    nameAr: "دجاج بالزبدة (ماخان والا)",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Jal Ferezi",
    nameAr: "دجاج جال فريزي",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken 65",
    nameAr: "دجاج ٦٥",
    desc: "",
    price: "33",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Lemon Chicken",
    nameAr: "دجاج بالليمون",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chilly Chicken",
    nameAr: "دجاج بالفل",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Manchurian",
    nameAr: "دجاج منشوروريان",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Green Pepper Chicken",
    nameAr: "دجاج بالفلفل الأخضر",
    desc: "",
    price: "30",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Honey Garlic Chicken",
    nameAr: "دجاج بالعسل والثوم",
    desc: "",
    price: "35",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Schezwan Chicken",
    nameAr: "دجاج سشوان",
    desc: "",
    price: "35",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Methi Malai Chicken",
    nameAr: "دجاج بالحلبة والكريمة",
    desc: "",
    price: "35",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Lemon Pepper Chicken",
    nameAr: "دجاج بالليمون والفلفل",
    desc: "",
    price: "33",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Murg Tikka Massala",
    nameAr: "دجاج تكة مسالا",
    desc: "",
    price: "35",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Chicken Roghan",
    nameAr: "دجاج روغان",
    desc: "",
    price: "33",
    category: "Main Course",
    categoryAr: "الأطباق الرئيسية",
  },
  {
    name: "Mutton Fry",
    nameAr: "لحم مقلي",
    desc: "",
    price: "38",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Mutton Badami",
    nameAr: "لحم باللوز",
    desc: "",
    price: "35",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Mutton Masala",
    nameAr: "لحم مسالا",
    desc: "",
    price: "32",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Mutton Khorma",
    nameAr: "لحم كورما",
    desc: "",
    price: "32",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Mutton Kadai",
    nameAr: "لحم كاداي",
    desc: "",
    price: "32",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Mutton Roghan",
    nameAr: "لحم روغان جـوش",
    desc: "",
    price: "32",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Mairaj Special Mutton",
    featured: true,
    nameAr: "لحم معراج الخاص",
    desc: "",
    price: "38",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Pudina Mutton",
    nameAr: "لحم بالنعناع",
    desc: "",
    price: "38",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Meat Balls",
    nameAr: "كفتة لحم",
    desc: "",
    price: "31",
    category: "Mutton Items",
    categoryAr: "أطباق اللحم",
  },
  {
    name: "Zeera Aloo Fry",
    nameAr: "بطاطس مقلية بالكمون",
    desc: "",
    price: "17",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Aloo Mutter",
    nameAr: "بطاطس مع بسلة",
    desc: "",
    price: "17",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Corn Masala",
    nameAr: "ذرة مسالا",
    desc: "",
    price: "15",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Mushroom Masala",
    nameAr: "فطر مسالا",
    desc: "",
    price: "18",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Mix Vegetable",
    nameAr: "خضار مشكل",
    desc: "",
    price: "17",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Vegetable Makhanwala",
    nameAr: "خضار بالزبدة",
    desc: "",
    price: "17",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Paneer Butter Masala",
    nameAr: "باذنيـر بالزبدة ومسالا",
    desc: "",
    price: "25",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Shahi Paneer",
    nameAr: "شاهي بانير",
    desc: "",
    price: "25",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Dal Butter Fry",
    nameAr: "عدس مقلي بالزبدة",
    desc: "",
    price: "14",
    category: "Vegetable & Dal",
    categoryAr: "الخضروات والعدس",
  },
  {
    name: "Fish Tikka",
    nameAr: "سمك تكة",
    desc: "",
    price: "30",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Fish Fry",
    nameAr: "سمك مقلي",
    desc: "",
    price: "30",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Chilly Fish",
    nameAr: "سمك بالفلفل الحار",
    desc: "",
    price: "33",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Fish Masala",
    nameAr: "سمك مسالا",
    desc: "",
    price: "30",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Golden Fried Prawns",
    featured: true,
    nameAr: "روبيان مقلي ذهبي",
    desc: "",
    price: "46",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Prawns Zabardast",
    image: prawnsZabardastImg,
    nameAr: "روبيان زبردست",
    desc: "",
    price: "44",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Chilly Prawns",
    nameAr: "روبيان بالفلفل الحار",
    desc: "",
    price: "46",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Lemon Prawns",
    nameAr: "روبيان بالليمون",
    desc: "",
    price: "46",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Prawns Manchurian",
    nameAr: "روبيان مانتشوريان",
    desc: "",
    price: "46",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Honey Garlic Prawns",
    nameAr: "روبيان بالعسل والثوم",
    desc: "",
    price: "46",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Kadai Prawns",
    nameAr: "روبيان كاداي",
    desc: "",
    price: "44",
    category: "Seafood",
    categoryAr: "المأكولات البحرية",
  },
  {
    name: "Mutton Biryani",
    image: muttonBiryaniImg,
    nameAr: "برياني لحم",
    desc: "",
    price: "28",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Chicken Biryani",
    featured: true,
    image: chickenBiryaniImg,
    nameAr: "برياني دجاج",
    desc: "",
    price: "20",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Prawns Biryani",
    nameAr: "برياني روبيان",
    desc: "",
    price: "40",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Fried Rice Chicken",
    nameAr: "أرز مقلي بالدجاج",
    desc: "",
    price: "18",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Fried Rice Vegetable",
    nameAr: "أرز مقلي بالخضار",
    desc: "",
    price: "15",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Darbari Biryani",
    nameAr: "برياني دربار",
    desc: "",
    price: "25",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Zeera Rice",
    nameAr: "أرز بالكمون",
    desc: "",
    price: "12",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Plain Rice",
    nameAr: "أرز أبيض (سادة)",
    desc: "",
    price: "6",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Biryani Rice",
    nameAr: "أرز برياني",
    desc: "",
    price: "12",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Green Salad",
    nameAr: "سلطة خضراء",
    desc: "",
    price: "6",
    category: "Salads",
    categoryAr: "السلطات",
  },
  {
    name: "Russian Salad",
    nameAr: "سلطة روسية",
    desc: "",
    price: "9",
    category: "Salads",
    categoryAr: "السلطات",
  },
  {
    name: "Mix Raitha",
    nameAr: "رائتة مشكلة (زبادي بالخضار)",
    desc: "",
    price: "5",
    category: "Salads",
    categoryAr: "السلطات",
  },
  {
    name: "Fatush",
    nameAr: "فتوش",
    desc: "",
    price: "8",
    category: "Salads",
    categoryAr: "السلطات",
  },
  {
    name: "Mix Pickle",
    nameAr: "مخلل مشكل",
    desc: "",
    price: "6",
    category: "Salads",
    categoryAr: "السلطات",
  },
  {
    name: "Kaju biryani",
    nameAr: "برياني الكاجو",
    desc: "",
    price: "14",
    category: "Rice",
    categoryAr: "الأرز",
  },
  {
    name: "Roti",
    nameAr: "خبز تندوري",
    desc: "",
    price: "3",
    category: "Tandoori Basket",
    categoryAr: "سلة التندوري",
  },
]

export const categories = Array.from(new Set(menu.map((m) => m.category)))